source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'SlackTextViewControllerTests'
inhibit_all_warnings!

platform :ios, '7.0'

pod 'SlackTextViewController', :path => '../'

pod 'Expecta+Snapshots', '1.3.2'
pod 'Specta', '0.5.0'