source 'https://github.com/CocoaPods/Specs.git'

workspace 'Messenger.xcworkspace'
link_with 'Messenger-Programatic', 'Messenger-Programatic-iPad-Sheet', 'Messenger-Storyboard', 'Messenger-Swift'
platform :ios, '7.0'

pod 'SlackTextViewController', :path => '../../SlackTextViewController.podspec'

pod 'LoremIpsum', '~> 1.0'